## S3
default: &default
  AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  S3_BUCKET_NAME: <%= ENV['S3_BUCKET_NAME'] %>
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
