# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  ct_oauth_token: <%= ENV['CT_OAUTH_TOKEN'] %>
  mandrill_api_key: <%= ENV['MANDRILL_API_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio_sid: <%= ENV['TWILIO_SID'] %>
  twilio_token: <%= ENV['TWILIO_TOKEN'] %>

test:
  secret_key_base: 528ba5dca85f8d91592829eb53913171fd5bfb24d53a84aae2b7ee5ff10648ebb0208647489b3811aeaaa23779a7ab2059bb68d2b9d0e36ed1e6e07d4c358aa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  ct_oauth_token: <%= ENV['CT_OAUTH_TOKEN'] %>
  mandrill_api_key: <%= ENV['MANDRILL_API_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio_sid: <%= ENV['TWILIO_SID'] %>
  twilio_token: <%= ENV['TWILIO_TOKEN'] %>

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
